# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 30

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels: []

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
# onlyLabels:
#   - TestLabel

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 2

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This pull request has been automatically marked as stale because it didn't have any recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This pull request is closed. Thank you.

  @import url('https://fonts.googleapis.com/css?family=Poppins');
html, body {
    margin: 0;
    padding: 0;
}
body {
  font-family: 'Poppins';
}
header > div {
    padding: 0 25px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid lightgray;
}
nav {
  width: 600px;  
}
nav ul {
    list-style: none;
    display: flex;
    justify-content: space-between;
    align-items: center;
}
nav a {
    text-decoration: none;
    color: black;
}
.blackheart {
    width: 20px;
    margin-right: 1rem;
}
.nav-bar {
    padding: 10px 25px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}
.logo {
    width: 30px;
} 
.glass {
    width: 30px;
}
#search,label{
  background-color:  rgba(0,0,0,.05);
  width: 1000px;
}
#label {
    color: rgba(0,0,0,.05);
}
.button {
    background-color: #fb3e44;
    color: white;
}
#Join {
    text-decoration: none;
    color: grey;
    border: 1px solid grey;
}
.border #Join {
    padding: 3px
} 
.nav-bar #login {
    text-decoration: none;
    color: grey;  
    margin-right: 20px; 
}
#section1 {
    height: 600px;
    background-color:  rgba(232,217,217,.3) ;
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
}
h1 {
    font-size: 100px;
    margin-top: 10px;
}
#article1 {
    font-size: 25px;
    text-align: center;
}
#seeplans .plans {
    background-color: #FB3B49;
    text-decoration: none;
    color: white;
    margin-right: 50px;
    font-size: 50px;
    box-shadow: 8px 8px 0 rgba(251,59,73,2);
}
#seeplans .free {
    text-decoration: none;
    color: black;
    font-size:50px ;
}
#section2 {
    height: 600px;
    background-color:  rgba(232,217,217,.3) ;
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;  
}
h2 {
    background-color: rgba(255,204,53,.4);
    font-size: 30px;
}
#article2 {
    transform: skew(9deg,0deg);
    font-style: italic;
    font-size: 20px;
    margin: 60px 100px 30px 100px;
    padding: 0 50px;
    text-align: center;
}
h3 {
   color: #ED1C24;

}
.org {
    text-decoration: none;
    color:white;
    background-color: black;
    box-shadow: 8px 8px 0 rgba(128,83,35,.2);
}
.zero {
    width: 30px;
}
.team {
    width: 30px;
}
.family {
    width: 30px;
}
.audi {
    width: 30px;
}
#section3 > div {
    font-size: 11px;
    text-align: center;
}
#section3 .org {
    font-weight: 200px;
    font-size:30px;
    margin-left: 600px;
    padding-right: 50px;
    padding-left: 50px;
}
